points.d               ! name of output file containing points
0.26234526             ! random number
500                    ! number of points in scatterer (subvolume 1)
2                      ! type of scatterer (subvolume 1)
20                     ! dimensions (subvolume 1)
100                    ! dimensions (subvolume 1)
0 0                    ! rotation of subvolume 1
0 0 0                  ! translation of subvolume 1
Y                      ! new subvolume [Y]es or [N]o
1                      ! type of scatterer (subvolume 2)
50                     ! dimensions (subvolume 2)
0 0                    ! rotation of subvolume 2
0 0 75                 ! translation of subvolume 2
Y                      ! new subvolume [Y]es or [N]o
1                      ! type of scatterer (subvolume 2)
50                     ! dimensions (subvolume 2)
0 0                    ! rotation of subvolume 2
0 0 -75                ! translation of subvolume 2
N                      ! new subvolume [Y]es or [N]o


